global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'solicitud-service'
    static_configs:
      - targets: ['solicitud-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/status'
    scrape_interval: 10s